add p6.md
NCU-CSIE-Algorithmics-A-1061/Homework-6 pull request #6
Opened 2017-10-30 16:05 UTC by scps940707

2017-10-30 16:07 UTC, c910335 requested changes

2017-10-30 16:07 UTC, c910335 commented on p6.md
> +10. ![](https://i.imgur.com/uunQgSm.jpg)
Use text instead of image.

2017-10-30 16:21 UTC, c910335 requested changes
Why the author of this commit is ncuoolab?

2017-10-31 04:34 UTC, scps940707 commented
@c910335 
author fixed

2017-11-02 15:59 UTC, merged